class Solution {
public:
    string intToRoman(int num) {
        string res="";
        while(num!=0){
            if(num>=1000){
                res+='M';
                num-=1000;
                continue;
            }
            if(num<1000&&num>=900){
                res+='C'+'M';
                num-=900;
                continue;
            }
            if(num<900&&num>=500){
                res+='D';
                num-=500;
                continue;
            }
            if(num<500&&num>=400){
                res+='C'+'D';
                num-=400;
                continue;
            }
            if(num<400&&num>=100){
                res+='C';
                num-=100;
                continue;
            }
            if(num<100&&num>=90){
                res+='X'+'C';
                num-=90;
                continue;
            }
            if(num<90&&num>=50){
                res+='L';
                num-=50;
                continue;
            }
            if(num<50&&num>=40){
                res+='X'+'L';
                num-=40;
                continue;
            }
            if(num<40&&num>=10){
                res+='X';
                num-=10;
                continue;
            }
            if(num==9){
                res+='I'+'X';
                num-=9;
                continue;
            }
            if(num<9&&num>)
        }
        
    }
};